version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: gunicorn snapfood.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./Backend/.env
    depends_on:
      - db
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./Frontend/src:/code/src:ro
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Backend/.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8001:80
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
