# Generated by Django 5.0 on 2023-12-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد تخفیف')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expire_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='قیمت کل')),
                ('total_price_with_discount', models.IntegerField(verbose_name='قیمت کل با تخفیف')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='تحویل داده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='امتیاز')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.comment', verbose_name='پاسخ')),
            ],
        ),
    ]
