# Generated by Django 5.0 on 2023-12-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price_with_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='مقدار تخفیف'),
        ),
    ]
