# Generated by Django 5.0 on 2023-12-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('delivery_price', models.IntegerField(verbose_name='هزینه ارسال')),
                ('is_open', models.BooleanField(default=True, verbose_name='باز است؟')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('foods', models.ManyToManyField(blank=True, to='food.food', verbose_name='غذاها')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantcategory', verbose_name='دسته بندی')),
            ],
        ),
    ]
